Dev-Abdelrhman/Task-Management

- packages/Frontend/src/App.jsx
> chore: Add comment for commit test in App component

- packages/Frontend/src/App.jsx
> chore: Remove commented-out code in App component

- packages/Backend/controllers/authControllers.js
- packages/Backend/strategies/google_Strategy.js
- packages/Frontend/src/api/auth.js
- packages/Frontend/src/component/pages/auth/completeSigninGoogle.jsx
Trying fix the error in Google auth but it looks like it form the front not the backend
> Backend_Development

- packages/Frontend/src/api/auth.js
- packages/Frontend/src/component/pages/auth/GoogleCallback.jsx
- packages/Frontend/src/component/pages/auth/completeSigninGoogle.jsx
- packages/Frontend/src/hooks/useAuth.js
- packages/Frontend/src/utils/ProtectedRoutes.jsx
> Enhance Google signup flow by streamlining API calls, improving error handling, and updating navigation logic

- packages/Backend/controllers/authControllers.js
- packages/Frontend/src/api/auth.js
- packages/Frontend/src/component/pages/auth/GoogleCallback.jsx
- packages/Frontend/src/hooks/useAuth.js
- packages/Frontend/src/stores/authStore.js
- packages/Frontend/src/utils/ProtectedRoutes.jsx
Enhance the robustness of API requests by implementing better error handling and logging mechanisms. This ensures that failures are managed gracefully and provides clearer insights during debugging.
> last fix to google auth flow

- packages/Backend/controllers/authControllers.js
- packages/Backend/routes/userRoute.js
- packages/Backend/strategies/google_Strategy.js
- packages/Backend/strategies/passport_Config.js
- packages/Frontend/src/hooks/useAuth.js
- packages/Frontend/src/stores/authStore.js
Clean up the Google authentication code, enhance error handling, and update API endpoint URLs for better functionality.
> Refactor Google authentication flow and improve error handling

- API_Documentation.json
- packages/Backend/app.js
- packages/Backend/controllers/handlerFactory.js
Streamline JSON responses for consistency, enhance rate limiting configuration with improved input sanitization, and introduce a new endpoint for retrieving user information via Google authentication.
> Refactor response handling and add Google user info endpoint

- packages/Frontend/package.json
- packages/Frontend/src/component/pages/Dashboard.jsx
- packages/Frontend/src/index.css
Add Swiper for upcoming tasks in Dashboard; refactor styles and improve layout. Clean up unused CSS and enhance user experience with new date formatting and task progress indicators.
> ui improvement

- packages/Frontend/src/api/auth.js
- packages/Frontend/src/component/pages/Dashboard.jsx
- packages/Frontend/src/component/pages/Projects/Projects.jsx
Refactor authentication logic in API; implement request and response interceptors for token management and error handling. Adjust Dashboard styles for better UI consistency and add user ID logging in Projects component.
> Auth Refresh Token fix and hot fix in dashboard ui

- packages/Frontend/src/api/auth.js
- packages/Frontend/src/api/project.js
- packages/Frontend/src/component/pages/AddProjectBtn.jsx
- packages/Frontend/src/component/pages/Projects/Projects.jsx
Refactor authentication API calls to streamline endpoint structure and improve project management UI. Update AddProjectBtn component to handle project data more efficiently and enhance user experience with improved form handling. Remove unnecessary state management in Projects component and integrate project fetching with React Query.
> project functionality improve

- packages/Backend/controllers/authControllers.js
- packages/Backend/models/projectsModel.js
- packages/Backend/models/userModel.js
Eliminate the refresh token functionality from the authentication controller. Update slug generation in the projects model to include a timestamp, and enhance the public_id field in the user model with type, trim, and lowercase options.
> Remove refresh token functionality and enhance models

- packages/Frontend/src/api/project.js
- packages/Frontend/src/component/pages/AddProjectBtn.jsx
- packages/Frontend/src/component/pages/ProjectOptionsMenu.jsx
- packages/Frontend/src/component/pages/Projects/Projects.jsx
integrate delete function and update with modal
> integrate delete function and update with modal 

- packages/Frontend/index.html
- packages/Frontend/src/component/pages/AddProjectBtn.jsx
- packages/Frontend/src/component/pages/ProjectOptionsMenu.jsx
updating modal for editing,delete
> updating index.html , modal for editing , delete

- packages/Frontend/src/component/pages/Dashboard.jsx
- packages/Frontend/src/component/pages/Projects/ProjectOptionsMenu.jsx
- packages/Frontend/src/component/pages/Projects/Projects.jsx
Enhance loading and error handling in Dashboard and Projects components; refactor project deletion confirmation logic for improved user experience.
> fix bugs in dashboard and projects

- packages/Backend/controllers/authControllers.js
- packages/Backend/controllers/commentControllers.js
- packages/Backend/controllers/handlerFactory.js
- packages/Backend/controllers/projectsControllers.js
- packages/Backend/controllers/tasksControllers.js
- packages/Backend/controllers/userControllers.js
- packages/Backend/models/commentModel.js
- packages/Backend/models/projectsModel.js
- packages/Backend/models/tasksModel.js
- packages/Backend/models/userModel.js
- packages/Backend/routes/commentRoute.js
- packages/Backend/routes/projectsRoute.js
- packages/Backend/routes/tasksRoute.js
- packages/Backend/utils/multer.js
Streamline image upload processes by centralizing handling in the handler factory, updating relevant models and routes to accommodate image uploads, and ensuring proper deletion of associated images.
> Refactor image upload handling across controllers and models

- .github/CODEOWNERS
- packages/Frontend/ToDo.txt
- packages/Frontend/index.html
- packages/Frontend/src/api/auth.js
- packages/Frontend/src/component/pages/Dashboard.jsx
- packages/Frontend/src/component/pages/Home.jsx
- packages/Frontend/src/component/pages/auth/completeSigninGoogle.jsx
- packages/Frontend/src/stores/projectStore.js
Update CODEOWNERS, change page title to 'Taskord', simplify auth error handling, and refactor image hosting in Dashboard and Google Sign-in components. Remove unused project store methods.
> hotfix and update fix refresh token error 

- packages/Frontend/src/App.jsx
- packages/Frontend/src/api/project.js
- packages/Frontend/src/component/pages/Projects/ProjectDetails.jsx
- packages/Frontend/src/component/pages/Projects/ProjectTasks.jsx
- packages/Frontend/src/component/pages/Projects/Projects.jsx
- packages/Frontend/src/stores/authStore.js
- packages/Frontend/vite.config.js
create project details component
> create project details component

- API_Documentation.json
- Postman_Collections/Task_Management.postman_collection.json
- packages/Backend/controllers/auth.Controller.js
- packages/Backend/controllers/user.Controller.js
- packages/Backend/models/project.Model.js
- packages/Backend/routes/invite.Route.js
- packages/Backend/routes/projects.Route.js
- packages/Backend/routes/tasks.Route.js
- packages/Backend/routes/user.Route.js
- packages/Backend/server.js
Improve API documentation, streamline user and project routes, enhance user image handling, and refactor authentication and user controllers for better maintainability and clarity.
> Enhance API documentation and improve user handling

- package.json
- packages/Frontend/package.json
- packages/Frontend/src/api/user_tasks.js
- packages/Frontend/src/component/pages/Projects/Projects.jsx
- packages/Frontend/src/component/pages/User_Tasks/AddTask.jsx
- packages/Frontend/src/component/pages/User_Tasks/AllTasks.jsx
- packages/Frontend/src/utils/socket.js
- Added socket.io-client as a dependency in package.json.
- Implemented socket connection in socket.js for real-time communication.
- Created AddTask component for adding new tasks with a modal.
- Integrated task creation functionality in AllTasks component using React Query.
- Updated task management logic to handle task states (Pending, Todo, In Progress, Done).
- Refactored Projects component for better readability and structure.
- Added error handling and loading states in task fetching and creation.
> feat: Add socket.io-client and implement task management features

- packages/Backend/controllers/Factory.Controller.js
- packages/Backend/controllers/auth.Controller.js
- packages/Backend/routes/comments.Route.js
- packages/Backend/routes/tasks.Route.js
- packages/Backend/utils/requireProjectPermission.js
Refactor the permission checking logic for projects, ensuring it handles cases where project IDs may not be present. Remove unused code and streamline the permission verification process.
> Refactor permission checks and clean up unused code in project utility

- packages/Frontend/ToDo.txt
- packages/Frontend/package.json
- packages/Frontend/src/api/auth.js
- packages/Frontend/src/component/pages/Dashboard.jsx
- packages/Frontend/src/component/pages/Projects/ProjectOptionsMenu.jsx
- packages/Frontend/src/component/pages/Projects/Projects.jsx
- packages/Frontend/src/component/pages/auth/ForgetPassword.jsx
- packages/Frontend/src/component/pages/auth/Login.jsx
- packages/Frontend/src/component/pages/auth/PasswordMeter.jsx
- packages/Frontend/src/component/pages/auth/SignUp.jsx
- packages/Frontend/src/shared/Sidebar.jsx
- packages/Frontend/src/stores/authStore.js
feat: Enhance authentication pages with improved UI and password strength meter
- Updated ForgetPassword component with a new header and improved layout.
- Added ListTodo icon to the header for branding.
- Enhanced form styling and user feedback for password reset functionality.
- Refactored Login component for better structure and visual consistency.
- Integrated PasswordStrengthMeter in SignUp component to provide real-time feedback on password strength.
- Improved PasswordMeter component with better styling and criteria checks.
- Updated Sidebar navigation links for better user experience.
- Cleaned up authStore by removing unnecessary comments.
> refactior for ui pages and some imporvements 

- packages/Frontend/src/App.jsx
- packages/Frontend/src/api/projectTasks.js
- packages/Frontend/src/component/pages/Projects/AddProjectTask.jsx
- packages/Frontend/src/component/pages/Projects/ProjectDetails.jsx
- packages/Frontend/src/component/pages/Projects/ProjectTasks.jsx
- packages/Frontend/src/component/pages/Projects/Projects.jsx
- packages/Frontend/src/component/pages/User_Tasks/AllTasks.jsx
- Organized & created  ProjectTasks component
- Created Add Project Task component
- Added functionality to add, update, and delete tasks
- Used socket.io for real-time task updates
- Added drag & drop feature to move tasks between columns
> Create and Manage Project Tasks with Realtime Updates and Drag & Drop

- packages/Backend/controllers/projects.Controller.js
- packages/Backend/models/project.Model.js
- packages/Backend/models/task.Model.js
- packages/Frontend/src/component/pages/Dashboard.jsx
- packages/Frontend/src/component/pages/Projects/Projects.jsx
- packages/Frontend/src/component/pages/User_Tasks/AllTasks.jsx
Introduce progress tracking for projects and enhance the user interface for better project and task management.
> Enhance project and task management with progress tracking and improved UI

- packages/Backend/app/controllers/Factory.Controller.js
Streamline the `updateOne` function by eliminating redundant options in the `findByIdAndUpdate` method, enhancing code clarity and maintainability.
> Simplify updateOne function by removing unnecessary options

- API_Documentation.json
- packages/Backend/app/models/task.Model.js
Introduce a new field for task completion notes in the task model and update the API documentation accordingly.
> Add developerNote field to task model and API documentation

- packages/Backend/app.js
- packages/Backend/app/utils/multer.js
- packages/Frontend/src/component/pages/Dashboard.jsx
- packages/Frontend/src/component/pages/Projects/Projects.jsx
Increase the JSON body parser limit to accommodate larger requests and adjust the multer temporary file deletion timeout. Refactor the Dashboard and Projects components to display project categories instead of descriptions.
> Update JSON body parser limit and refactor project description to category

- packages/Frontend/src/api/projectTasks.js
- packages/Frontend/src/component/pages/Projects/AddProjectTask.jsx
- packages/Frontend/src/component/pages/Projects/ProjectDetails.jsx
- packages/Frontend/src/component/pages/Projects/ProjectTasks.jsx
update projectDetails(editing tasks
creating modal for each task
> update projectDetails(editing tasks)

- packages/Frontend/src/component/pages/Projects/ProjectTasks.jsx
> handle updating tasks

- packages/Backend/app/controllers/error.Controller.js
Enhance error messages for better clarity and introduce additional error handling for version conflicts and MongoDB connection issues in production.
> Improve error handling and add new error cases for production

- packages/Backend/app/models/role.Model.js
- packages/Frontend/package.json
Correct the default color value in the role schema and remove theCreator from the JSON transformation.
> Fix role schema default color and JSON transformation

- API_Documentation.json
- packages/Backend/app/controllers/projects.Controller.js
- packages/Backend/routes/projects.Route.js
Introduce a new endpoint to fetch members of a specific project, enhancing the API's functionality.
> Add endpoint to retrieve project members

- Postman_Collections/Task_Management.postman_collection.json
- packages/Backend/routes/projects.Route.js
Eliminate the unused route for accessing project members to streamline the codebase. This change enhances clarity and maintainability.
> Remove unused route for project members

- packages/Backend/app.js
- packages/Backend/app/controllers/projects.Controller.js
- packages/Backend/app/utils/rateLimite.js
- packages/Backend/routes/roles.Route.js
- packages/Backend/routes/user.Route.js
Introduce rate limiting for user authentication and general requests, enhancing security and performance. Update project retrieval to include role selection for improved data access.
> Implement rate limiting and role selection in project retrieval

- packages/Backend/app/controllers/Factory.Controller.js
- packages/Backend/routes/comments.Route.js
- packages/Backend/routes/roles.Route.js
Refactor the code to ensure that ownership checks are enforced for comments and roles routes, enhancing authorization security.
> Enforce ownership checks in comments and roles routes

- API_Documentation.json
- packages/Backend/app/models/invite.Model.js
- packages/Backend/app/utils/requireProjectPermission.js
Update API documentation URLs for invite endpoints and improve the population of the invite model to include additional user details.
> Refactor invite API documentation and enhance model population

- packages/Backend/app/controllers/invite.Controller.js
Enhance the search results for user invites by including user images and streamline the accept invite function by removing unnecessary whitespace.
> Include user image in invite search results and clean up invite acceptance logic

- packages/Backend/app/controllers/invite.Controller.js
Update the project population in the sendInvite function to include member users instead of just the owner.
> Refactor project population in sendInvite function

- packages/Backend/app/controllers/invite.Controller.js
Update the permission check in the sendInvite function to verify project members instead of just the owner.
> Refactor sendInvite permission check

- packages/Frontend/package.json
- packages/Frontend/src/App.jsx
- packages/Frontend/src/api/invite.js
- packages/Frontend/src/api/project.js
- packages/Frontend/src/component/pages/Invite/InviteManagement.jsx
- packages/Frontend/src/component/pages/Invite/InviteModal.jsx
- packages/Frontend/src/component/pages/Projects/ProjectDetails.jsx
- packages/Frontend/src/component/pages/Projects/Projects.jsx
- packages/Frontend/src/component/pages/Setting.jsx
- packages/Frontend/src/hooks/useInvite.js
- packages/Frontend/src/shared/Sidebar.jsx
feat: add invite management feature with sender and receiver invite handling
- Implemented Sidebar navigation link for invites.
- Created API functions for managing invites (get, send, accept, decline, delete).
- Developed InviteManagement component for displaying and managing sent and received invites.
- Added InviteModal for searching users and sending invites with role selection.
- Introduced useInvite hook for managing invite-related queries and mutations.
> feat: add invite management feature with sender and receiver invite handling

- packages/Frontend/src/component/pages/Dashboard.jsx
- packages/Frontend/src/component/pages/Invite/InviteManagement.jsx
- packages/Frontend/src/component/pages/Invite/InviteModal.jsx
- packages/Frontend/src/component/pages/Projects/ProjectDetails.jsx
- packages/Frontend/src/component/pages/Projects/Projects.jsx
feat: enhance project and invite management UI with improved member display and status indicators
> feat: enhance project and invite management UI with improved member display and status indicators

- API_Documentation.json
- packages/Backend/app/models/project.Model.js
- packages/Frontend/src/shared/Navbar.jsx
Introduce a function to format user image URLs for display and enhance API documentation with a structured outline for socket events, enabling real-time updates.
> Add user image formatting and socket events structure to API documentation

- packages/Backend/app/controllers/auth.Controller.js
- packages/Backend/app/controllers/user.Controller.js
- packages/Backend/app/models/user.Model.js
Improve the password update functionality by adding validation for input fields and enhancing error handling for various scenarios, including user not found and incorrect current password.
> Enhance password update process with validation and error handling

- packages/Backend/app/controllers/Factory.Controller.js
Update event broadcasting to consistently use the 'io' instance from the app configuration, enhancing real-time event handling across the application.
> Standardize event broadcasting using 'io' instance

- packages/Backend/app/controllers/user.Controller.js
Ensure the `updateMe` function returns the updated user document by setting the `new` option to true in the `findByIdAndUpdate` method.
> Fix updateMe function to return the updated user document

- packages/Backend/app/utils/eventLogger.js
Change label color in the displayEvent function to hex format for enhanced visibility.
> Improve displayEvent function label color for visibility

- packages/Backend/app/models/comment.Model.js
Correct the user field selection in the comment model to include the user ID during population.
> Fix user field selection in comment model population

- packages/Backend/app/controllers/Factory.Controller.js
- packages/Backend/app/controllers/comments.Controller.js
- packages/Backend/app/controllers/projects.Controller.js
- packages/Backend/app/controllers/roles.Controller.js
- packages/Backend/app/controllers/tasks.Controller.js
- packages/Backend/app/controllers/user.Controller.js
- packages/Backend/app/utils/cloudinary.js
Standardize image folder names across various controllers and enhance the user profile update logic, including improved error messages and handling for image uploads.
> Refactor image handling and user profile updates

- packages/Backend/app/models/project.Model.js
Introduce a virtual status property to the project schema to indicate the current state of tasks based on their progress and due date.
> Add virtual status property to project schema for task progress tracking

- API_Documentation.json
Introduce new fields for project type and status in the API documentation to enhance clarity and usability.
> Add project type and status fields to API documentation

- API_Documentation.json
- packages/Backend/app.js
- packages/Backend/app/controllers/Factory.Controller.js
- packages/Backend/app/controllers/auth.Controller.js
- packages/Backend/app/controllers/user.Controller.js
- packages/Backend/app/models/project.Model.js
- packages/Backend/app/models/task.Model.js
Refactor the API documentation by removing unused routes and enhancing model validation requirements. This update streamlines the codebase and ensures that all necessary fields are validated correctly.
> Refactor API documentation and improve model validation

- packages/Frontend/src/component/pages/Projects/ProjectDetails.jsx
- packages/Frontend/src/component/pages/Projects/Projects.jsx
Redesigned comment UI, 
enabled socket connection,
and implemented reply feature
> Redesigned comment UI,  enabled socket connection,  and implemented reply feature

- packages/Frontend/package.json
- packages/Frontend/src/api/auth.js
- packages/Frontend/src/component/pages/Dashboard.jsx
- packages/Frontend/src/component/pages/Projects/ProjectDetails.jsx
- packages/Frontend/src/component/pages/User_Tasks/AllTasks.jsx
- packages/Frontend/src/shared/Navbar.jsx
Add recharts for activity visualization, enhance error handling in auth API, and improve dashboard UI
> chart in dashboard and sockets of role and auth improve

- API_Documentation.json
- packages/Frontend/src/component/pages/Dashboard.jsx
- packages/Frontend/src/component/pages/Projects/Projects.jsx
Enhance real-time project updates with socket integration in Dashboard and Projects components
> projects socket

- API_Documentation.json
- packages/Backend/app/controllers/auth.Controller.js
- packages/Backend/routes/user.Route.js
Implement OTP handling in the signup and verification process, including a new endpoint for OTP verification and updated API documentation.
> Add OTP verification for signup process

- packages/Backend/package.json
Enhance the robustness of user authentication by implementing better error handling and logging mechanisms. This update aims to provide clearer feedback to users and facilitate easier debugging for developers.
> Improve error handling in user authentication

- packages/Frontend/src/api/auth.js
- packages/Frontend/src/component/pages/auth/ForgetPassword.jsx
- packages/Frontend/src/component/pages/auth/GoogleCallback.jsx
- packages/Frontend/src/component/pages/auth/Login.jsx
- packages/Frontend/src/component/pages/auth/ResetPassword.jsx
- packages/Frontend/src/component/pages/auth/SignUp.jsx
- packages/Frontend/src/component/pages/auth/completeSigninGoogle.jsx
- packages/Frontend/src/component/pages/auth/verifyEmail.jsx
- packages/Frontend/src/component/pages/dashboard/ActivityChart.jsx
- packages/Frontend/src/component/pages/dashboard/DashboardNav.jsx
- packages/Frontend/src/component/pages/dashboard/RunningTask.jsx
- packages/Frontend/src/hooks/useAuth.js
refactor: Simplify authentication API calls and improve error handling
- Refactored authentication API functions for better readability and performance.
- Updated error handling in response interceptors to return error objects instead of strings.
- Streamlined user-related API calls by removing unnecessary async/await where not needed.
- Enhanced the useAuth hook to provide clearer error messages and improved user feedback.
- Updated various components to reflect changes in API function signatures and error handling.
> refactor: Simplify authentication API calls and improve error handling

- packages/Frontend/src/component/pages/auth/AuthForm.jsx
- packages/Frontend/src/component/pages/auth/AuthLayout.jsx
- packages/Frontend/src/component/pages/auth/Login.jsx
- packages/Frontend/src/component/pages/auth/SignUp.jsx
Refactor SignUp component to use AuthLayout and AuthForm for improved structure and readability; added form handling and validation logic.
> Refactor SignUp component to use AuthLayout and AuthForm for improved structure and readability; added form handling and validation logic.

- packages/Frontend/src/hooks/useTaskMutations.js
Enhance error handling mechanisms for API requests to provide clearer feedback and improve debugging capabilities.
> Improve error handling in API requests

- packages/Frontend/src/api/projectTasks.js
- packages/Frontend/src/assets/assets.js
- packages/Frontend/src/component/pages/Invite/InviteModal.jsx
- packages/Frontend/src/component/pages/Projects/ProjectCard/ProjectFilters.jsx
- packages/Frontend/src/component/pages/Projects/ProjectCard/ProjectSection.jsx
- packages/Frontend/src/component/pages/Projects/ProjectDetails/components/Comments.jsx
- packages/Frontend/src/component/pages/Projects/ProjectDetails/components/ProjectHeader.jsx
- packages/Frontend/src/component/pages/Projects/ProjectDetails/components/RoleModal.jsx
- packages/Frontend/src/component/pages/Projects/ProjectModals/AddProjectBtn.jsx
- packages/Frontend/src/component/pages/Projects/ProjectModals/DeleteProjectModal.jsx
- packages/Frontend/src/component/pages/Projects/projectTasks/ProjectTasks.jsx
- packages/Frontend/src/component/pages/auth/AuthLayout.jsx
- packages/Frontend/src/component/pages/auth/Login.jsx
- packages/Frontend/src/component/pages/auth/ResetPassword.jsx
- packages/Frontend/src/component/pages/dashboard/ActivityChart.jsx
- packages/Frontend/src/component/pages/dashboard/RightSidebar.jsx
- packages/Frontend/src/hooks/boards/useBoardManagement.js
- packages/Frontend/src/hooks/tasks/useTaskManagement.js
- packages/Frontend/src/hooks/tasks/useTaskMutations.js
- packages/Frontend/src/main.jsx
Enhance the user authentication process by streamlining login and registration, improving error handling, and adding validation checks. This update aims to provide a smoother user experience and increase security measures.
> Improve user authentication flow and improve code over all 

- packages/Frontend/src/component/pages/Home/components/Hero.jsx
- packages/Frontend/src/component/pages/Settings/Setting.jsx
- packages/Frontend/src/component/pages/Settings/modals/DeleteUserModal.jsx
- packages/Frontend/src/component/pages/Settings/taps/SecuritySettings.jsx
- packages/Frontend/src/hooks/users/useUserInfo.js
Enhance the user authentication process by streamlining login and registration, improving error handling, and adding validation checks. This update aims to provide a smoother user experience and increase security measures.
> Improve user authentication flow and improve code over all
